"""SQL statements of the project module: one small function per statement.

Every function takes an ``AsyncSession`` whose transaction the *caller* (the
service) already began; a function never commits, rolls back, opens a
transaction, sets a timeout or catches an error. Locks are the caller's
business too, except where a docstring says a function locks. No function here
authorizes anything or decides a rule: rules live in ``domain.py`` and
``service.py``. Arguments are already validated (UUIDs, aware UTC datetimes,
enum members), so a function never validates or coerces them.

Statements are written with SQLAlchemy Core against the tables below (never
with string formatting of values). The helper functions ``project_from_row`` and
``member_from_row`` turn a result row into the records; a function that
"returns a Project" returns exactly what the row holds after the statement.

IMPLEMENTATION NOTE (PAW-026 stubs): every ``async def`` below is a stub.
Replace the ``raise NotImplementedError`` with the statement its docstring
describes. Do not change a signature or a docstring. Do not commit.
"""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from paw_backend.authz.roles import ProjectRole
from paw_backend.identity.models import UserRow
from paw_backend.projects.models import ProjectMemberRow, ProjectRow
from paw_backend.projects.records import (
    Member,
    MemberStatus,
    PendingInvite,
    Project,
    ProjectStatus,
)

PROJECTS = ProjectRow.__table__
MEMBERS = ProjectMemberRow.__table__
USERS = UserRow.__table__


def project_from_row(row: Any) -> Project:
    """A :class:`Project` from a row of ``PROJECTS`` (any object with its columns)."""
    return Project(
        id=row.id,
        name=row.name,
        description=row.description,
        status=ProjectStatus(row.status),
        created_by=row.created_by,
        created_at=row.created_at,
        updated_at=row.updated_at,
        deletion_started_at=row.deletion_started_at,
        deletion_scheduled_at=row.deletion_scheduled_at,
        deleted_at=row.deleted_at,
    )


def member_from_row(row: Any) -> Member:
    """A :class:`Member` from a row of ``MEMBERS`` (any object with its columns)."""
    return Member(
        project_id=row.project_id,
        user_id=row.user_id,
        role=ProjectRole(row.role),
        status=MemberStatus(row.status),
        invited_at=row.invited_at,
        invite_expires_at=row.invite_expires_at,
        joined_at=row.joined_at,
    )


# --- projects ------------------------------------------------------------------


async def get_project(
    session: AsyncSession, project_id: uuid.UUID, *, for_update: bool = False
) -> Project | None:
    """The project with this id in **any** status (a tombstone too), or ``None``.

    With ``for_update=True`` the statement is ``SELECT ... FOR UPDATE`` (it
    waits for a row lock held by another transaction), which is how every
    changing operation of the service starts. Nothing else is locked.
    """
    raise NotImplementedError("PAW-026 stub")


async def insert_project(
    session: AsyncSession,
    *,
    name: str,
    description: str | None,
    created_by: uuid.UUID,
    now: datetime,
) -> Project:
    """Insert a new ACTIVE project and return it.

    The id is generated by the database (``gen_random_uuid()``, the column
    default). ``created_at`` and ``updated_at`` are both ``now``; the three
    deletion columns are ``None``.
    """
    raise NotImplementedError("PAW-026 stub")


async def update_settings(
    session: AsyncSession,
    project_id: uuid.UUID,
    *,
    name: str,
    description: str | None,
    now: datetime,
) -> Project:
    """Set ``name`` and ``description`` and ``updated_at = now``; return the project.

    Nothing else changes (not the status). ``sqlalchemy.exc.NoResultFound`` if
    there is no such project.
    """
    raise NotImplementedError("PAW-026 stub")


async def set_lifecycle(
    session: AsyncSession,
    project_id: uuid.UUID,
    *,
    status: ProjectStatus,
    deletion_started_at: datetime | None,
    deletion_scheduled_at: datetime | None,
    now: datetime,
) -> Project:
    """Set ``status``, both deletion timestamps and ``updated_at = now``.

    ``None`` for a deletion timestamp clears it.

    Returns the project. The name, the description and ``deleted_at`` are not
    touched. ``sqlalchemy.exc.NoResultFound`` if there is no such project.
    """
    raise NotImplementedError("PAW-026 stub")


async def mark_deleted(
    session: AsyncSession, project_id: uuid.UUID, *, now: datetime
) -> Project:
    """Turn the project into its tombstone and return it.

    ``status = DELETED``, ``deleted_at = now``, ``updated_at = now``,
    ``name = paw_backend.projects.limits.DELETED_PROJECT_NAME``,
    ``description = None``. ``created_by``, ``created_at`` and both deletion
    timestamps keep their values. ``sqlalchemy.exc.NoResultFound`` if there is
    no such project.
    """
    raise NotImplementedError("PAW-026 stub")


async def select_due_project_ids(
    session: AsyncSession, now: datetime, limit: int
) -> list[uuid.UUID]:
    """Ids of Pending deletion projects that are due at ``now``, oldest first.

    Due means ``status = 'pending_deletion'`` and ``deletion_scheduled_at <=
    now`` (equal counts). At most ``limit`` ids, ordered by
    ``deletion_scheduled_at`` then ``id``. The rows are locked with
    ``FOR UPDATE SKIP LOCKED``: a project another transaction holds a lock on
    is silently left out, and the statement never waits.
    """
    raise NotImplementedError("PAW-026 stub")


async def count_due_projects(session: AsyncSession, now: datetime) -> int:
    """How many Pending deletion projects are due at ``now`` (same rule as above).

    Plain ``count``: no lock and no ``SKIP LOCKED``.
    """
    raise NotImplementedError("PAW-026 stub")


# --- members and invitations -------------------------------------------------------


async def get_member(
    session: AsyncSession, project_id: uuid.UUID, user_id: uuid.UUID
) -> Member | None:
    """The membership row (accepted or invited, expired or not) or ``None``."""
    raise NotImplementedError("PAW-026 stub")


async def insert_member(session: AsyncSession, member: Member) -> Member:
    """Insert ``member`` exactly as given and return the stored row as a Member.

    A row for the same ``(project_id, user_id)`` violates the primary key
    (``sqlalchemy.exc.IntegrityError``, not handled here).
    """
    raise NotImplementedError("PAW-026 stub")


async def activate_invite(
    session: AsyncSession,
    project_id: uuid.UUID,
    user_id: uuid.UUID,
    *,
    joined_at: datetime,
) -> Member:
    """Turn an INVITED row into an ACTIVE one and return it.

    ``status = ACTIVE``, ``joined_at = joined_at``, ``invite_expires_at =
    None``; ``role`` and ``invited_at`` are kept. Only an INVITED row is
    changed: ``sqlalchemy.exc.NoResultFound`` when there is no row or it is
    ACTIVE already.
    """
    raise NotImplementedError("PAW-026 stub")


async def set_member_role(
    session: AsyncSession,
    project_id: uuid.UUID,
    user_id: uuid.UUID,
    role: ProjectRole,
) -> Member:
    """Set the role of an ACTIVE member and return the row.

    Only an ACTIVE row is changed (an invitation's role is never changed):
    ``sqlalchemy.exc.NoResultFound`` when there is no such ACTIVE row.
    """
    raise NotImplementedError("PAW-026 stub")


async def delete_member(
    session: AsyncSession, project_id: uuid.UUID, user_id: uuid.UUID
) -> bool:
    """Delete the row of this user in this project (any status).

    ``True`` if a row was deleted, ``False`` if there was none. Other rows are
    never touched.
    """
    raise NotImplementedError("PAW-026 stub")


async def delete_project_members(session: AsyncSession, project_id: uuid.UUID) -> int:
    """Delete every row (accepted members and invitations) of one project.

    Returns how many rows were deleted (``0`` for none). Rows of other projects
    are never touched.
    """
    raise NotImplementedError("PAW-026 stub")


async def list_active_members(
    session: AsyncSession, project_id: uuid.UUID
) -> list[Member]:
    """The ACTIVE members of one project, ordered by ``joined_at`` then ``user_id``."""
    raise NotImplementedError("PAW-026 stub")


async def list_open_invites(
    session: AsyncSession, project_id: uuid.UUID, now: datetime
) -> list[Member]:
    """The open invitations of one project at ``now``.

    Ordered by ``invited_at``, then ``user_id``.

    Open means ``status = 'invited'`` and ``invite_expires_at > now`` (an
    invitation whose expiry equals ``now`` is expired and is left out).
    """
    raise NotImplementedError("PAW-026 stub")


async def count_members(
    session: AsyncSession, project_id: uuid.UUID, now: datetime
) -> int:
    """ACTIVE members plus open invitations of one project at ``now``.

    Expired invitations are not counted.
    """
    raise NotImplementedError("PAW-026 stub")


# --- what one user sees ----------------------------------------------------


async def list_projects_of(
    session: AsyncSession,
    user_id: uuid.UUID,
    status: ProjectStatus,
    limit: int,
    offset: int,
) -> list[Project]:
    """The projects in ``status`` in which ``user_id`` is an ACTIVE member.

    An invitation does not make a project visible. For ``PENDING_DELETION``
    only the projects where the user's role is ``MANAGER`` are returned (only a
    Manager can restore); for the other statuses every role sees the project.
    Ordered by ``created_at`` newest first, then ``id`` ascending; ``limit`` and
    ``offset`` are applied after the ordering.
    """
    raise NotImplementedError("PAW-026 stub")


async def roles_of(
    session: AsyncSession, user_id: uuid.UUID
) -> dict[uuid.UUID, ProjectRole]:
    """``{project_id: role}`` of the ACTIVE memberships of ``user_id``.

    Only projects whose status is not ``DELETED`` (invitations never count).
    An empty dict for a user without membership.
    """
    raise NotImplementedError("PAW-026 stub")


async def list_open_invites_of(
    session: AsyncSession, user_id: uuid.UUID, now: datetime
) -> list[PendingInvite]:
    """The open invitations addressed to ``user_id`` at ``now``.

    Open means ``status = 'invited'`` and ``invite_expires_at > now``, and the
    project's status is ``ACTIVE`` or ``ARCHIVED`` (an invitation to a Pending
    deletion or Deleted project is not shown). ``PendingInvite.project_name`` is
    the project's name, ``expires_at`` the invitation's ``invite_expires_at``.
    Ordered by ``invited_at`` then ``project_id``.
    """
    raise NotImplementedError("PAW-026 stub")


async def user_is_active(session: AsyncSession, user_id: uuid.UUID) -> bool:
    """Whether ``users`` has a row with this id and ``status = 'active'``."""
    raise NotImplementedError("PAW-026 stub")
