"""Agent Task lifecycle: states, commands and their persistence (PAW-032).

There is no HTTP surface yet: authentication and RBAC (PAW-022 / PAW-025) come
first. See ``apps/backend/README.md`` for the state machine and the data model.
The Project state gate (``ProjectGate``, Issue #83) is the one place where the task
lane looks at a project; ``projects.task_gate`` implements it.
"""

from paw_backend.tasks.domain import (
    CONTROL_COMMANDS,
    TERMINAL_STATES,
    TRANSITIONS,
    Actor,
    ActorKind,
    Interruption,
    RepoRole,
    TaskCommand,
    TaskRun,
    TaskState,
    WaitReason,
    WorkingSetOperation,
    allowed_commands,
    interruption_of,
    plan_transition,
)
from paw_backend.tasks.errors import (
    CompletionRequirementsNotMetError,
    IllegalTransitionError,
    InvalidCommandArgumentError,
    LastTargetRemovalRefusedError,
    ModifiedRepositoryDowngradeRefusedError,
    NoTargetRepositoryError,
    ProjectNotActiveError,
    RepositoryNotInAttemptError,
    RepositoryRoleInsufficientError,
    RepositoryRoleUnresolvedError,
    RepositoryWriteHolderAliveError,
    RepositoryWriteInFlightError,
    RepositoryWriteNotFoundError,
    RepositoryWriteNotHeldError,
    StaleAttemptError,
    StaleRunError,
    TaskConflictError,
    TaskError,
    TaskNotActiveError,
    TaskNotFoundError,
    TaskNotRunningError,
    TaskStateChangedError,
    TaskStepError,
    WorkingSetChangeInvalidError,
    WorkingSetConflictError,
    WorkingSetError,
)
from paw_backend.tasks.project_gate import ProjectGate
from paw_backend.tasks.records import (
    AttemptRepositorySnapshot,
    AttemptSnapshot,
    EvaluationResult,
    LogEntry,
    LogLevel,
    PullRequestInfo,
    PullRequestState,
    RepositoryChangeState,
    ReviewState,
    ReviewStatus,
    StepInfo,
    StepStatus,
    TaskEvent,
    TaskSnapshot,
    ToolInvocationInfo,
    ToolInvocationStatus,
    WorkingSetEntry,
    WorkingSetRepository,
    WorktreeState,
)
from paw_backend.tasks.service import InTransactionStep, TaskService, TransitionListener
from paw_backend.tasks.working_set import (
    FailClosedChangeInspector,
    RepositoryChangeInspector,
)

__all__ = [
    "CONTROL_COMMANDS",
    "TERMINAL_STATES",
    "TRANSITIONS",
    "Actor",
    "ActorKind",
    "AttemptRepositorySnapshot",
    "AttemptSnapshot",
    "CompletionRequirementsNotMetError",
    "EvaluationResult",
    "FailClosedChangeInspector",
    "IllegalTransitionError",
    "InTransactionStep",
    "Interruption",
    "InvalidCommandArgumentError",
    "LastTargetRemovalRefusedError",
    "LogEntry",
    "LogLevel",
    "ModifiedRepositoryDowngradeRefusedError",
    "NoTargetRepositoryError",
    "ProjectGate",
    "ProjectNotActiveError",
    "PullRequestInfo",
    "PullRequestState",
    "RepoRole",
    "RepositoryChangeInspector",
    "RepositoryChangeState",
    "RepositoryNotInAttemptError",
    "RepositoryRoleInsufficientError",
    "RepositoryRoleUnresolvedError",
    "RepositoryWriteHolderAliveError",
    "RepositoryWriteInFlightError",
    "RepositoryWriteNotFoundError",
    "RepositoryWriteNotHeldError",
    "ReviewState",
    "ReviewStatus",
    "StaleAttemptError",
    "StaleRunError",
    "TaskStateChangedError",
    "TaskNotRunningError",
    "StepInfo",
    "StepStatus",
    "TaskCommand",
    "TaskConflictError",
    "TaskError",
    "TaskEvent",
    "TaskNotActiveError",
    "TaskNotFoundError",
    "TaskRun",
    "TaskService",
    "TaskSnapshot",
    "TaskState",
    "TaskStepError",
    "ToolInvocationInfo",
    "ToolInvocationStatus",
    "TransitionListener",
    "WaitReason",
    "WorkingSetChangeInvalidError",
    "WorkingSetConflictError",
    "WorkingSetEntry",
    "WorkingSetError",
    "WorkingSetOperation",
    "WorkingSetRepository",
    "WorktreeState",
    "allowed_commands",
    "interruption_of",
    "plan_transition",
]
