"""Agent Task lifecycle: states, commands and their persistence (PAW-032).

There is no HTTP surface yet: authentication and RBAC (PAW-022 / PAW-025) come
first. See ``apps/backend/README.md`` for the state machine and the data model.
"""

from paw_backend.tasks.domain import (
    CONTROL_COMMANDS,
    TERMINAL_STATES,
    TRANSITIONS,
    Actor,
    ActorKind,
    Interruption,
    TaskCommand,
    TaskState,
    WaitReason,
    allowed_commands,
    interruption_of,
    plan_transition,
)
from paw_backend.tasks.errors import (
    IllegalTransitionError,
    InvalidCommandArgumentError,
    StaleAttemptError,
    TaskConflictError,
    TaskError,
    TaskNotFoundError,
    TaskStepError,
)
from paw_backend.tasks.records import (
    AttemptSnapshot,
    EvaluationResult,
    LogEntry,
    LogLevel,
    PullRequestInfo,
    PullRequestState,
    ReviewState,
    ReviewStatus,
    StepInfo,
    StepStatus,
    TaskEvent,
    TaskSnapshot,
    ToolInvocationInfo,
    ToolInvocationStatus,
    WorktreeState,
)
from paw_backend.tasks.service import TaskService, TransitionListener

__all__ = [
    "CONTROL_COMMANDS",
    "TERMINAL_STATES",
    "TRANSITIONS",
    "Actor",
    "ActorKind",
    "AttemptSnapshot",
    "EvaluationResult",
    "IllegalTransitionError",
    "Interruption",
    "InvalidCommandArgumentError",
    "LogEntry",
    "LogLevel",
    "PullRequestInfo",
    "PullRequestState",
    "ReviewState",
    "ReviewStatus",
    "StaleAttemptError",
    "StepInfo",
    "StepStatus",
    "TaskCommand",
    "TaskConflictError",
    "TaskError",
    "TaskEvent",
    "TaskNotFoundError",
    "TaskService",
    "TaskSnapshot",
    "TaskState",
    "TaskStepError",
    "ToolInvocationInfo",
    "ToolInvocationStatus",
    "TransitionListener",
    "WaitReason",
    "WorktreeState",
    "allowed_commands",
    "interruption_of",
    "plan_transition",
]
