"""Shared Codex / Claude connections, per-user quotas and attributed usage (PAW-030).

A backend library on PostgreSQL: no HTTP endpoint, no network call, no process. See
``apps/backend/README.md`` ("Shared Codex / Claude Connection") and Decision 0016.
"""

from paw_backend.connections.adapter import (
    AdapterFailure,
    AdapterRegistry,
    AdapterRequest,
    AdapterResult,
    ConnectionAdapter,
    validate_adapter,
)
from paw_backend.connections.domain import (
    UNLIMITED,
    ConnectionKind,
    ConnectionStatus,
    FailureCode,
    QuotaMetric,
    QuotaPeriod,
    RefusalReason,
    Unlimited,
    UsagePurpose,
    UsageStatus,
    window_end,
    window_start,
)
from paw_backend.connections.errors import (
    AdapterInterfaceError,
    AdapterRegistryError,
    ConnectionBusyError,
    ConnectionCallError,
    ConnectionExistsError,
    ConnectionNotFoundError,
    ConnectionPermissionDeniedError,
    ConnectionsError,
    ConnectionUnavailableError,
    DuplicateAdapterError,
    InputProblem,
    InvalidConnectionInputError,
    QuotaExceededError,
    QuotaNotConfiguredError,
    TargetUserNotFoundError,
    TaskBudgetError,
    TaskNotUsableError,
    UnknownAdapterError,
)
from paw_backend.connections.records import (
    ConnectionAvailability,
    ConnectionInfo,
    ConnectionRequest,
    ConnectionResult,
    Quota,
    QuotaUsage,
    UsageRecord,
)
from paw_backend.connections.secret import Secret, SecretResolver
from paw_backend.connections.service import ConnectionService
from paw_backend.connections.store import ConnectionStore

__all__ = [
    "UNLIMITED",
    "AdapterFailure",
    "AdapterInterfaceError",
    "AdapterRegistry",
    "AdapterRegistryError",
    "AdapterRequest",
    "AdapterResult",
    "ConnectionAdapter",
    "ConnectionAvailability",
    "ConnectionBusyError",
    "ConnectionCallError",
    "ConnectionExistsError",
    "ConnectionInfo",
    "ConnectionKind",
    "ConnectionNotFoundError",
    "ConnectionPermissionDeniedError",
    "ConnectionRequest",
    "ConnectionResult",
    "ConnectionService",
    "ConnectionStatus",
    "ConnectionStore",
    "ConnectionUnavailableError",
    "ConnectionsError",
    "DuplicateAdapterError",
    "FailureCode",
    "InputProblem",
    "InvalidConnectionInputError",
    "Quota",
    "QuotaExceededError",
    "QuotaMetric",
    "QuotaNotConfiguredError",
    "QuotaPeriod",
    "QuotaUsage",
    "RefusalReason",
    "Secret",
    "SecretResolver",
    "TargetUserNotFoundError",
    "TaskBudgetError",
    "TaskNotUsableError",
    "UnknownAdapterError",
    "Unlimited",
    "UsagePurpose",
    "UsageRecord",
    "UsageStatus",
    "validate_adapter",
    "window_end",
    "window_start",
]
